{
    'name': 'MySchool Theme',
    'summary': 'Teal-based backend theme for MySchool',
    'version': '19.0.2.0.2',
    'category': 'Themes/Backend',
    'license': 'LGPL-3',
    'author': 'MySchool',
    'depends': [
        'web',
        'base_setup',
        'mail',
    ],
    'post_init_hook': 'post_init_hook',
    'data': [
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            (
                'after',
                'web/static/src/scss/primary_variables.scss',
                'myschool_theme/static/src/scss/colors.scss',
            ),
        ],
        'web.assets_backend': [
            'myschool_theme/static/src/scss/layout.scss',
            'myschool_theme/static/src/scss/components.scss',
            'myschool_theme/static/src/scss/appsmenu.scss',
            'myschool_theme/static/src/scss/navbar.scss',
            'myschool_theme/static/src/scss/sidebar.scss',
            'myschool_theme/static/src/xml/navbar.xml',
            'myschool_theme/static/src/xml/sidebar.xml',
            'myschool_theme/static/src/xml/webclient.xml',
            'myschool_theme/static/src/js/appsmenu.js',
            'myschool_theme/static/src/js/navbar.js',
            'myschool_theme/static/src/js/sidebar.js',
            'myschool_theme/static/src/js/webclient.js',
            'myschool_theme/static/src/js/chatter_toggle.js',
            'myschool_theme/static/src/scss/chatter.scss',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
